format_version: '4'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git

trigger_map:
  - push_branch: '*'
    pipeline: test-on-Ubuntu-and-Xcode-stacks
pipelines:
  test-on-Ubuntu-and-Xcode-stacks:
    stages:
      - test-stacks: {}
stages:
  test-stacks:
    workflows:
      - test-on-Ubuntu-stack: {}
      - test-on-Xcode-stack: {}

meta:
  bitrise.io:
    stack: linux-docker-android-22.04
    machine_type_id: standard

workflows:
  test-on-Ubuntu-stack:
    meta:
      bitrise.io:
        stack: linux-docker-android-22.04
    steps:
      - activate-ssh-key@4: {}
      - git-clone@8: {}
      - path::./:
          inputs:
            - api_key: $DATADOG_API_KEY
            - app_key: $DATADOG_APP_KEY
            - public_ids: '7uk-gte-ywv'

  test-on-Xcode-stack:
    meta:
      bitrise.io:
        stack: osx-xcode-edge
        machine_type_id: g2-m1.4core
    steps:
      - activate-ssh-key@4: {}
      - git-clone@8: {}
      - path::/Users/vagrant/git:
          inputs:
            - api_key: $DATADOG_API_KEY
            - app_key: $DATADOG_APP_KEY
            - public_ids: '7uk-gte-ywv'

  audit-this-step:
    steps:
      - script:
          inputs:
            - content: |-
                #!/bin/bash
                set -ex
                stepman audit --step-yml ./step.yml
