# This workflow automatically creates a release PR for the CI integration.

name: Push new relase version to Steplib Fork

env:
  GIT_AUTHOR_EMAIL: "packages@datadoghq.com"
  GIT_AUTHOR_NAME: "ci.datadog-ci"

on:
  - push
  # release:
  # types:
  #   - published

jobs:
  create-release-pr-for-steplb:
    runs-on: ubuntu-latest
    steps:
      # Do the changes
      - name: Get GitHub App token
        id: get-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.RELEASE_AUTOMATION_GITHUB_APP_ID }}
          private_key: ${{ secrets.RELEASE_AUTOMATION_GITHUB_APP_PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.get-token.outputs.token }}
      - name: Set git user
        run: |
          git config user.name "${GIT_AUTHOR_NAME}"
          git config user.email "${GIT_AUTHOR_EMAIL}"
      - name: Run script to create PR to bitrise-io/bitrise-steplib
        run: |
          RELEASE_VERSION=${{ github.event.release.tag_name }}
          RELEASE_VERSION="v$RELEASE_VERSION" # e.g. v1.1.0
          bitrise share start -c https://github.com/DataDog/bitrise-steplib.git
          bitrise share create --tag ${{ steps.bump-version.outputs.RELEASE_VERSION }} --git https://github.com/DataDog/synthetics-test-automation-bitrise-step-run-tests.git --stepid datadog-mobile-app-run-tests
          echo "PR ready to be created for ${{ steps.bump-version.outputs.RELEASE_VERSION }}"
        # bitrise share finish
